### PR TITLE
Update sendForm.d.ts

### PR DESCRIPTION
**Pull request by akneo1499**
Please remove the type keyword for EmailJSResponseStatus import it is showing me an error in my angular application.
If I remove this type keyword my project is working fine

### CODE REVIEW

**Comment by xr0master** [comment]
@akneo1499 thanks for your participation!
The code is valid and specifying the type can improve the packet size. I suggest that you update your typescript to use the type imports. Or you can add `"skipLibCheck": true,` to your `tsconfig.json`.

**Comment by akneo1499** [comment]
The solutions you told me do not resolve my problem. You can't apply skipLibCheck to node modules.
Is there any way by which I can resolve this issue?
@xr0master

**Comment by akneo1499** [comment]
$ ng build
ERROR in node_modules/emailjs-com/es/index.d.ts:1:13 - error TS1005: '=' expected.
1 import type { EmailJSResponseStatus } from './models/EmailJSResponseStatus';
node_modules/emailjs-com/es/index.d.ts:1:44 - error TS1005: ';' expected.
1 import type { EmailJSResponseStatus } from './models/EmailJSResponseStatus';
node_modules/emailjs-com/es/index.d.ts:5:1 - error TS1128: Declaration or statement expected.
5 export type { EmailJSResponseStatus };
node_modules/emailjs-com/es/index.d.ts:5:13 - error TS1005: ';' expected.
5 export type { EmailJSResponseStatus };
node_modules/emailjs-com/es/methods/send/send.d.ts:1:13 - error TS1005: '=' expected.
1 import type { EmailJSResponseStatus } from '../../models/EmailJSResponseStatus';
node_modules/emailjs-com/es/methods/send/send.d.ts:1:44 - error TS1005: ';' expected.
1 import type { EmailJSResponseStatus } from '../../models/EmailJSResponseStatus';
node_modules/emailjs-com/es/methods/sendForm/sendForm.d.ts:1:13 - error TS1005: '=' expected.
1 import type { EmailJSResponseStatus } from '../../models/EmailJSResponseStatus';
node_modules/emailjs-com/es/methods/sendForm/sendForm.d.ts:1:44 - error TS1005: ';' expected.
1 import type { EmailJSResponseStatus } from '../../models/EmailJSResponseStatus';

**Comment by xr0master** [comment]
There is no problem with this SDK, I am sure you can find a solution to your problems on the Internet. You can also use REST API instead of SDK.

**Pull request closed without merging**
