### PR TITLE
fix: update key name from 'user_id' to 'public_key' #issue38

### PR DESCRIPTION
**Pull request by azazack**
the issue is its still uses a user_id params after being update to public key three month 
Screen Shot 2022-07-21 at 13 30 40
Screen Shot 2022-07-21 at 13 31 27

### CODE REVIEW

**Review by arnonrdp — APPROVED** [review]

**Comment by azazack** [comment]
@arnonrdp can you merge it ? thanks.

**Comment by arnonrdp** [comment]
Sorry, I am not part of the team.
I just reviewed and approved your PR to confirm that we NEED this improvement.

**Comment by xr0master** [comment]
At the moment the code works correctly, I will close this PR. Thanks for your cooperation.

**Comment by azazack** [comment]
@xr0master can you double check please ? me and @arnonrdp we are facing the same issue, and i shared the screen with you.

**Comment by xr0master** [comment]
Yes, I am 100% sure. If you have an issue, it definitely does not relate to the operation of the SDK.

**Pull request closed without merging**
